[package]
name = "wsl2windows-runner"
description = "A runner for building in WSL2 and running output .exe in Windows"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
